import Head from "next/head";
import MainLayout from "shared/mainlayout";
import ProfilePage from "pages/profilepage";
import AboutMePage from "./aboutme";
import MyProjectPage from "./myproject";

const Home: React.FunctionComponent<{}> = (props) => {
    return (
      <div>
        <Head>
          <title>Popo Fianto</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="favicon.png" />
        </Head>
        <MainLayout>
          <ProfilePage />
          <AboutMePage />
          <MyProjectPage />
        </MainLayout>
        <footer></footer>
      </div>
    );
};

export default Home;
