import Head from "next/head";
import MainLayout from "shared/mainlayout";
import ProfilePage from "pages/profilepage";
import AboutMePage from "./aboutme";
import MyProjectPage from "./myproject";
import ContactMePage from "./contactme";

const Home: React.FunctionComponent<{}> = (props) => {
    return (
      <div className="dark">
        <Head>
          <title>Popo Fianto</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="favicon.png" />
          <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet"></link>
        </Head>
        <MainLayout>
          <ProfilePage />
          <AboutMePage />
          <MyProjectPage />
          <ContactMePage />
        </MainLayout>
        <footer className="footers">
          <div className="container">
            <div className="row mx-auto">
              <p className="copyright col-lg-6">
                © 2022 Popo Fianto &bull; All Right Reserved
              </p>
              <p className="powered col-lg-6">
                Powered by Next.js
              </p>
            </div>
          </div>
        </footer>
      </div>
    );
};

<p>Hello</p>

export default Home;
